name: club_event_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # REST API холбох
  http: ^1.2.0

  # State management
  provider: ^6.1.2

  # Token хадгалах
  shared_preferences: ^2.5.5

  # Navigation system
  go_router: ^14.2.0
  google_fonts: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true