# Generated by Django 5.1.7 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('approved', 'Баталгаажсан'), ('rejected', 'Татгалзсан')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Оюутан'), ('school_admin', 'Сургуулийн админ')], default='student', max_length=20),
        ),
    ]
