# Generated by Django 6.0.1 on 2026-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_school_address_alter_school_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Оюутан'), ('school_admin', 'Сургуулийн админ'), ('club_leader', 'Клубын ахлагч'), ('teacher', 'Багш')], default='student', max_length=20),
        ),
    ]
