# Generated by Django 6.0.1 on 2026-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin_password',
            field=models.CharField(default=123, help_text='Админ хэрэглэгчийн түр нууц үг', max_length=128),
            preserve_default=False,
        ),
    ]
