# Generated by Django 6.0.1 on 2026-05-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Оюутан'), ('school_admin', 'Сургуулийн админ'), ('club_leader', 'Клубын ахлагч'), ('teacher', 'Багш'), ('admin', 'Админ')], default='student', max_length=20),
        ),
    ]
